name: YAML

on:
  push:

permissions:
  contents: read

jobs:
  yaml:
    name: yamlfmt & yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version: 1.24
      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@v0.21.0
      - name: yamlfmt
        run: yamlfmt -lint
      - name: Install yamllint
        run: pipx install yamllint==1.38.0
      - name: yamllint
        run: yamllint --strict .
